### ISSUE TITLE
What kind of work do you see yourself doing in 10 years?

### ISSUE THREAD

**Issue by NelsonMinar** [tmcw/ama#1]
Do you see yourself still programming? Working on open source/data projects? Maybe become a manager? Start a company? Quit working and tour with a band?

**Comment by tmcw** [comment]
I'd like to keep coding in some fashion as long as it interests me, which I think will be quite a while. I've been making things with computers since [2002](https://web.archive.org/web/20020803175119/http://www.njtrails.com/) and it's a pretty good gateway to a lot of different topics, music, math, geography, art, and so on. I'd really like to get better at other ways to make things, like drawing & electronics, and I think they'd mix with coding pretty well. More than anything, the multidisciplinary thing is what excites me, which is why I think [_why](http://viewsourcecode.org/why/) was so  cool.

Working in software, open source seems like a given, for the appropriate parts of the work product - libraries, raw parts, standards, and so on. I don't think it's really possible to work effectively anymore without contributing to it. I'm even more steadfast about open source than I was when I started at [Development Seed](https://developmentseed.org/) 6 years ago, but also way more open to closed source as part of your output. Products seem to be naturally closed combinations of naturally open parts.

Open data is cool, and it's really led me to meet some fascinating folks, but I feel less of a sense that I could stay working in that field forever. There's something immediate about creating systems that I miss when creating information.

As far as what I really _want_ to do, I've got inklings that it would be interesting to work on assistive devices, like [what Sabi has been doing](https://twitter.com/Sabi_brand/), or on programming interfaces for non-programmers. Mary Rose Cook's [Isla](http://islalanguage.org/) project, for instance, is really fascinating, as is [Workflow](https://workflow.is/). That whole "visual programming" challenge is kind of like a Siren luring programmers into an amazing but impossible future - everyone tries, but it's a really hard nut to crack. I'd at least want to give it a shot, because the problem of "simplifying programming" gives you a pretty great understanding of what programming is in the first place.

To make those kinds of things happen I might want to start a company. It really depends, though - in 10 years there could be grant-funding boom, or it might make sense to build solo and keep it small. It's rare nowadays, but I grew up seeing my dad run [a photo studio](http://macwrightstudio.com/) with two people and pretty clear goals, and it has outlasted a million startups.

I've edged towards more "management" at Mapbox, helping out with stuff like recruiting, writing the employee contract, leading teams, and that kind of stuff. The social side wipes me out: my quota for juggling people's needs and feelings is way lower than that of people who are good at that sort of thing. But 'management' is kind of a necessary thing if you're going to make anything bigger than a single person - in a way, open source project leaders are managers - and it's a skill I really want to master. It's been amazing to watch some of the people who are really, really good at running meetings do their thing, like Eric or Alex.

If Teen Mom decides to do a long tour, like 2 months on the road, I'll do it: I can work from the road, and tend to work pretty well when I've got solid breaks from typing that involve doing something totally different. It's kind of unlikely - we'd need to line up a booking agent, label, manager, publicist, and so on - but it's possible and exciting.

**Comment by NelsonMinar** [comment]
Great answer, I particularly liked your "what I really *want*" answer. On the theme of visual programming if somehow you haven't seen it, [Scratch](https://scratch.mit.edu/) is really amazing. You could do worse than spending a couple of years doing a master's degree with [Mitch Resnick](https://www.media.mit.edu/people/mres).
