### ISSUE TITLE
How do you do automated testing of a WebGL app?

### ISSUE THREAD

**Issue by danmactough** [tmcw/ama#2]
Have you found a solution you can live with? What are the components? Is there an off-the-shelf solution? Have you learned anything that can be distilled into something that will help others?

We (@socialtables) are just starting to look at automation with [electron](https://github.com/atom/electron), but this is looking to be a heavy lift.

**Comment by tmcw** [comment]
We're pretty far from the perfect approach, but here's where we are:

So, the application we're testing is "the app", basically the replacement for [Mapbox Studio](https://www.mapbox.com/mapbox-studio/). It's a React app focused on styling maps rendered with [Mapbox GL](https://www.mapbox.com/mapbox-gl/).

Basically we have split tests:

**app tests** only test react components and run in real web browsers always. we use [browserify](http://browserify.org/) to bundle our code, so we use it to bundle tests as well. Tests run with [tape](https://github.com/substack/tape) as a testing framework and run in real browsers using [smokestack](https://github.com/hughsk/smokestack). Smokestack replace [zuul](https://github.com/defunctzombie/zuul) because it really is the simplest thing possible: you put javascript in, you get console.log out. It's awesome, and really has been very reliable. tests run on [CircleCI](https://circleci.com/) and CircleCI doesn't quite parse [TAP](https://testanything.org/) output always, so we use [tap-status](https://github.com/tmcw/tap-status) to make the test command exit with a proper status.

All together, the testing script is

    "test": ". ./env_production.sh && npm run lint && (browserify test/headless.js -d | smokestack | tap-status) && retire"

(env_production sets some variables that are included in the source via [envify](https://github.com/hughsk/envify), and npm run lint just runs [eslint](http://eslint.org/))

The app **mocks** Mapbox GL in tests runs: we've written a [mock](https://gist.github.com/tmcw/eeb1a3d066f005ad32e9) that no-ops the necessary calls for this not to fail.

**Mapbox GL tests** on the other hand, actually need to render GL. These have a rather clever approach: they use the [headless-gl](https://github.com/mapbox/headless-gl) module to run gl [and wrap around it so that the code can run both in a browser and in node](https://github.com/mapbox/mapbox-gl-js/blob/master/test/gl.js). The tests render images which are then [exported as images with the pngjs module](https://github.com/mapbox/mapbox-gl-js/blob/master/test/render.test.js#L111) and compared to fixtures.

---

As far as I can tell, you cannot count on any cloud-hosted browser testing service to reliably have WebGL enabled. Sauce Labs failed hard in this regard, as did BrowserStack and Travis.

Given the slowness of Travis & the lack of GL support across everything, we're likely going to build our own CI which is little more than an EC2 stack wired up to SNS messages coming out of GitHub's organization hooks and writing to the [GitHub Commit Status API](https://github.com/blog/1227-commit-status-api).

_Local_ testing of GL is a much simpler equation - you could probably just use smokestack's existing screen capture API - but who tests locally nowadays.

**Comment by danmactough** [comment]
Thanks for such a thoughtful response.

> we're likely going to build our own CI

Yeah. I'm thinking we may coincidentally end up with a general purpose WebGL rendering farm that can be used for anything that we may as well make a product out of.

> use the headless-gl module to run gl and wrap around it so that the code can run both in a browser and in node. The tests render images which are then exported as images with the pngjs module and compared to fixtures.

When you do this, do the images created match what you would see in the browser in terms of geometry, fidelity, etc.? Or are they just "good enough for acceptance testing"? Would they be acceptable for pre-rendering user-facing thumbnail galleries, for example?

**Comment by tmcw** [comment]
> When you do this, do the images created match what you would see in the browser in terms of geometry, fidelity, etc.?

Yep: we also manually check the images to make sure that they're the same as browser reports. Luckily the [mapnik](http://mapnik.org/) team has been down this "fuzzy image comparison in order to power unit tests" rabbit hole for a while. The [GL tests write out a "difference" image for us to compare if tests fail](https://github.com/mapbox/mapbox-gl-js/blob/master/test/render.test.js#L150-L187), but for more intense testing, [mapnik actually has a visual image comparison api](http://mapnik.org/node-mapnik/documentation/#mapnik-image/compare)

**Comment by danmactough** [comment]
Sweet. I wonder if our Babel-transpiled front-end will and all the dependencies can run on node...

**Comment by tmcw** [comment]
:+1: here's to CI tools someday supporting WebGL :)
