### ISSUE TITLE
Why are you passionate about open source?

### ISSUE THREAD

**Issue by jseppi** [tmcw/ama#3]
You're obviously a staunch open source advocate and producer, and I'm just curious about the motivations for that support. Are there any influential leaders or authors that shaped your views?

**Comment by tmcw** [comment]
Everything I know about programming I learned from random people on the internet. I started with phpBB mods and TextPattern plugins. In college, I made a thing called [the Swem Signal](https://swem.wm.edu/um/swemsignal/) and participated in a sort of protozoic sharing which consisted of sharing the code with other libraries as a zip file. When I started at Development Seed, I maintained Drupal modules - my first real worldwide-collaborative experience.

I've always found it more interesting to work on general problems than to build websites, and general problems favor open source solutions.

So anyway, along the way there have been tons of people I've learned from. Getting to read everyone's code, everyone's English, to have civil discussions from time to time is everything.

I can still remember [this ticket in the modest maps repo in 2011](https://github.com/stamen/modestmaps-js/issues/17) where I naively suggested the whole project use jQuery, and had a discussion with Tom Carden & Mike Migurski - people on the other coast, working for totally different companies and using the library for totally different ways. Before that discussion I hadn't even thought of reading jQuery's code, or that such an abstraction wasn't always necessary: and within the course of those few days, really rethought my assumptions.

There are lots more like that - discussions that shaped my ideas, or attitudes. Working on OpenStreetMap, for instance, has really informed how I feel about collaborative communities in wildy positive and incredibly negative directions at different times.

Beyond the discussions, just being able to read code is such a gift. I've gotten pretty good at scanning large codebases quickly and getting an understanding of their style, functionality, and so on - seeing the different ways people solve the same problems is kind of an amazing lens into how they think and where the culture and style is going.

There are some trends that disappear in an instant. So many people used to do [vars-on-top](http://eslint.org/docs/rules/vars-on-top) and now practically nobody does. Almost nobody used the [string trick](https://github.com/mbostock/d3/blob/78e0a4bb81a6565bf61e3ef1b898ef8377478766/test/arrays/nest-test.js#L230) until d3 did, and now you see it more often. It's cool - even without changes to a programming language, style changes so fast. And I really think it changes quickly and en masse because of the ability for everyone to see everyone else's work.

And combining open source and business is still an unsolved problem I'm interested in. In the last year I've seen some companies doing a better job, but there are a lot of well-known, well-respected places that release absolutely none of the code they use in production, but consume so much.

At Mapbox, I've seen how company sponsorship affect projects positively and negatively, as well as how open and closed projects connect to form a product and separate concerns. I like the complexity. Working on this stuff every day, worrying about both releasing useful code and building a sustainable company is fascinating and hard and nothing like the sort of dogmatic feeling I used to have.

There are lots and lots of problems in open source, but they're mostly just the problems of real life, sometimes amplified or distorted by the power of the internet. People burn out, accusations of 'selling out' fly, good ideas don't gain traction, appearance matters too much. With a large enough company, you can get all of these problems without releasing any code.

Along the way there are lots of really influential people - some for how they have brokered the 'open source' thing but mostly just people I think have really pushed the space forward. That's people like Mary Rose Cook, Dean McNamee, Cindy Brewer, Tom Carden, Jacob Thorton, Alexis Sellier, Mike Bostock, why, Dane Springmeyer, and lots and lots of others.

Okay - that's... a ramble, happy to answer any follow-ups :)

**Comment by jseppi** [comment]
Thanks for nice response, @tmcw. I appreciate the commitment to open source that you and Mapbox have, and I've learned a great deal myself from reading your code.
